### ISSUE TITLE
Upstream request times

### ISSUE THREAD

**Issue by Ryuske** [iborodikhin/munin-plugin-nginx-upstream-multi#2]
I'm having an issue with the upstream request times graphs. They don't seem to be reading upstream response times correctly. I can see the times (in the correct format) in the log file, but the graph time graphs are blank and say -nan

**Comment by iborodikhin** [comment]
Please provide versions of nginx, munin-node and python and small piece of nginx log file.

**Comment by Ryuske** [comment]
This was over a year ago, I have no idea what the issue was but I have since found something that worked. I also have no idea what that thing is.
